#!/usr/bin/env python3
"""Plot only the committed per-panel data generated by the independent model."""
from pathlib import Path
import argparse
import json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap, SymLogNorm
from matplotlib.patches import Rectangle
from inventory import PANELS, GROUPS
from common import YEAR

plt.rcParams.update({'font.size':10.5,'axes.labelsize':10.5,'axes.titlesize':10.5,
    'legend.fontsize':8.5,'figure.dpi':120,'savefig.dpi':180,
    'pdf.fonttype':42,'ps.fonttype':42,'axes.spines.top':False,'axes.spines.right':False})
VELOCITY_CMAP=LinearSegmentedColormap.from_list('plate_rate',[(0,'#17345a'),(.4,'#f8f8f7'),(1,'#a31e2f')])
COLORS={'short':'#2779b9','baseline':'#d66b16','long':'#23a8a5','verylong':'#a1498b'}

def axes(fig,slot):return fig.add_subplot(slot)

def map_field(fig,ax,x,z,values,field,influx=3e-9):
    if field==1:
        shown=np.log10(np.maximum(np.abs(values),1e-30));cmap=VELOCITY_CMAP
        im=ax.pcolormesh(x,z/1000,shown.T,cmap=cmap,vmin=-15,vmax=0,shading='auto',rasterized=True)
        cb=fig.colorbar(im,ax=ax,pad=.02,extend='both');cb.set_ticks([-15,-12,-9,-6,-3,0]);cb.set_label(r'$\log_{10}|V|$ (m s$^{-1}$)')
    elif field==2:
        im=ax.pcolormesh(x,z/1000,values.T/1e6,cmap='viridis',shading='auto',rasterized=True)
        cb=fig.colorbar(im,ax=ax,pad=.02);cb.set_label('Effective stress (MPa)')
    elif field==3:
        im=ax.pcolormesh(x,z/1000,np.log10(values.T),cmap='viridis',shading='auto',rasterized=True)
        cb=fig.colorbar(im,ax=ax,pad=.02);cb.set_label(r'$\log_{10} k$ (m$^2$)')
    else:
        if values.min()>0:
            im=ax.pcolormesh(x,z/1000,np.log10(values.T),cmap='viridis',shading='auto',rasterized=True)
            cb=fig.colorbar(im,ax=ax,pad=.02);cb.set_label(r'$\log_{10} q$ (m s$^{-1}$)')
        else:
            scale=max(float(np.max(abs(values))),influx)
            im=ax.pcolormesh(x,z/1000,values.T,cmap='RdBu_r',norm=SymLogNorm(linthresh=influx*.05,vmin=-scale,vmax=scale,base=10),shading='auto',rasterized=True)
            cb=fig.colorbar(im,ax=ax,pad=.02);cb.set_label(r'Signed upward flux (m s$^{-1}$)')
    ax.set_ylim(z[-1]/1000,z[0]/1000);ax.set_ylabel('Depth (km)')
    return im

def render(fig,slot,name):
    spec=PANELS[name];kind=spec['kind'];d=np.load(spec['data_file'],allow_pickle=False)
    meta=json.loads(Path('data/panels',name+'.json').read_text())
    title=name+'  '+spec['quantity']
    if kind=='schematic':
        grid=slot.subgridspec(1,2,width_ratios=[1.5,1],wspace=.32);ax=axes(fig,grid[0]);fr=axes(fig,grid[1])
        ax.add_patch(Rectangle((0,0),1,1,facecolor='#eef3f6',edgecolor='#444444'))
        ax.add_patch(Rectangle((-.025,0),.05,1,facecolor='#95d5df',edgecolor='#156979'))
        for y in [.18,.4,.62,.84]:ax.annotate('',xy=(0,y+.1),xytext=(0,y),arrowprops=dict(arrowstyle='->',color='#156979',lw=1.5))
        ax.annotate('Plate loading\n$u=V_p t/2$',xy=(1,.55),xytext=(.55,.55),arrowprops=dict(arrowstyle='->'),ha='center')
        ax.text(.5,1.06,'Free surface; $p=0$',ha='center')
        ax.text(.5,-.10,'Traction-free base; upward influx $q_0$',ha='center')
        ax.text(.23,.2,'Elastic solid\n$L_y=L_z=500$ km',ha='left')
        ax.text(-.12,.5,'Fault: friction and fluid flow',rotation=90,ha='center',va='center')
        ax.text(.5,.87,'New schematic',ha='center',weight='bold')
        ax.text(.5,.78,'Not a simulation result',ha='center')
        ax.set(xlim=(-.25,1.1),ylim=(-.2,1.18));ax.axis('off')
        z=d['depth_m']/1000;fr.plot(d['a'],z,label='$a$');fr.plot(d['a']-d['b'],z,label='$a-b$')
        fr.axvline(0,color='.6',ls=':',lw=.7);fr.set(ylim=(25,0),xlabel='Assumed friction parameters',ylabel='Depth (km)');fr.legend();fr.set_title('F1a: geometry and inputs')
    elif kind=='stress_law':
        ax=axes(fig,slot)
        for power in [15,16,17,18]:ax.semilogy(d['effective_pa']/1e6,d['kstar_1e'+str(power)],label=r'$k_*=10^{-%d}$ m$^2$'%power)
        ax.axhline(1e-19,color='.5',ls=':',lw=.8)
        ax.set(xlabel='Effective normal stress (MPa)',ylabel='Permeability (m$^2$)',title=title);ax.legend()
    elif kind=='evolution_law':
        grid=slot.subgridspec(2,1,hspace=.55);top=axes(fig,grid[0]);bottom=axes(fig,grid[1])
        for p in [8,9,10]:top.semilogy(d['time_s']/YEAR,d['T_1e'+str(p)],label='$T={:.2f}$ yr'.format(10**p/YEAR))
        top.set(xlabel='Time without slip (yr)',ylabel='$k_*$ (m$^2$)',title='F1c: constitutive limiting solutions');top.legend()
        bottom.semilogy(d['slip_m'],d['kstar_m2']);bottom.set(xlabel='Slip with negligible healing (m)',ylabel='$k_*$ (m$^2$)')
        for ax in [top,bottom]:
            ax.set_ylim(6e-20,2e-15);ax.set_yticks([1e-19,1e-17,1e-15])
    elif kind=='steady':
        ax=axes(fig,slot);z=d['depth_m']/1000
        for key,label,style in [('pressure_pa','Pore pressure','-'),('effective_pa','Effective stress','-'),
                ('normal_pa','Assumed normal stress','--'),('hydrostatic_pa','Hydrostatic','--'),('lithostatic_pa','Lithostatic, 2700 kg/m³',':')]:
            ax.plot(d[key]/1e6,z,style,label=label)
        ax.set(xlabel='Pressure or stress (MPa)',ylabel='Depth (km)',ylim=(25,0),xlim=(0,450),title=title)
        ax.legend(loc='lower right');top=ax.twiny();top.semilogx(d['permeability_m2'],z,color='black',lw=1.4)
        top.set_xlabel('Steady permeability (m$^2$)');top.spines['top'].set_visible(True)
    elif kind=='fronts':
        ax=axes(fig,slot)
        for case in spec['cases']:
            t=d[case+'_time_years'];z=d[case+'_depth_m']/1000;v=np.maximum(abs(d[case+'_velocity']),1e-35)
            ax.contour(t,z,np.log10(v).T,levels=[np.log10(float(d[case+'_Vp']))],colors=[COLORS[case]],linewidths=.9)
            ax.plot([],[],color=COLORS[case],label='$T={:.3g}$ yr'.format(meta['selections'][case]['configuration']['T']/YEAR))
        ax.set(ylim=(25,0),xlabel='Time since selected window start (yr)',ylabel='Depth (km)',title='F6: independently generated $|V|=V_p$ contours')
        ax.legend();ax.text(.02,.98,'Contour definition is an analysis assumption',transform=ax.transAxes,va='top',fontsize=7)
    elif kind in ['velocity_pair','heatmap','step_heatmap']:
        t=(d['time_s']-float(d['origin_s']))/YEAR;step=d['step']-d['step'][0];z=d['depth_m'];field=int(d['field'])
        if kind=='velocity_pair':
            grid=slot.subgridspec(1,2,wspace=.4)
            for i,(xx,label) in enumerate([(t,'Time since window start (yr)'),(step,'Accepted integration step')]):
                ax=axes(fig,grid[i]);map_field(fig,ax,xx,z,d['values'],field,float(d['influx']));ax.set_xlabel(label)
                ax.set_title(name+': '+str(d['case'])+(' — time' if i==0 else ' — step'))
        else:
            ax=axes(fig,slot);xx=step if kind=='step_heatmap' else t
            map_field(fig,ax,xx,z,d['values'],field,float(d['influx']))
            ax.set_xlabel('Accepted integration step' if kind=='step_heatmap' else 'Time since window onset (yr)')
            ax.set_title(title)
        if meta['status']=='not reproduced':ax.text(.02,.03,'Target behavior not reproduced',transform=ax.transAxes,fontsize=7,
            bbox=dict(facecolor='white',alpha=.85,edgecolor='none'))
    elif kind in ['profiles','slip_profiles']:
        ax=axes(fig,slot);z=d['depth_m']/1000;field=int(d['field']);seen=set()
        for v,label in zip(d['profile_values'],d['profile_class']):
            color={'early':'.6','interseismic':'#2765b5','coseismic':'#c53428'}[str(label)]
            unit=1e6 if field==2 else 1
            ax.plot(v/unit,z,color=color,lw=.4,alpha=.75,label=str(label) if str(label) not in seen else None)
            seen.add(str(label))
        if kind!='slip_profiles':ax.plot(d['steady_values']/(1e6 if field==2 else 1),z,'k--',lw=1,label='Initial steady state')
        labels={0:'Cumulative slip since window start (m)',2:'Effective normal stress (MPa)',3:'Permeability (m$^2$)',5:'Upward flux (m s$^{-1}$)'}
        ax.set(xlabel=labels[field],ylabel='Depth (km)',ylim=(z[-1],z[0]),title=title)
        if field in [3,5]:
            if d['profile_values'].min()>0:ax.set_xscale('log')
            else:ax.set_xscale('symlog',linthresh=float(d['influx'])*.05)
        ax.legend(loc='best')
    elif kind=='depth_histories':
        ax=axes(fig,slot);t=(d['time_s']-float(d['origin_s']))/YEAR;field=int(d['field'])
        for j,depth in enumerate(d['depth_m']):
            vals=d['values'][:,j]
            if field==2:vals=vals/1e6
            if field==1:vals=np.maximum(np.abs(vals),1e-35)
            ax.plot(t,vals,lw=.65,label='{:.0f} km'.format(depth/1000),rasterized=True)
        if field==1:ax.set_yscale('log');ax.axhline(float(d['Vp']),ls=':',lw=.7,color='.4')
        if field in [3,5]:
            if d['values'].min()>0:ax.set_yscale('log')
            else:ax.set_yscale('symlog',linthresh=float(d['influx'])*.05)
        labels={1:'Slip speed (m s$^{-1}$)',2:'Effective stress (MPa)',3:'Permeability (m$^2$)',5:'Upward flux (m s$^{-1}$)'}
        ax.set(xlabel='Time since window onset (yr)',ylabel=labels[field],title=title);ax.legend(ncol=4)
    else:raise ValueError(kind)

def save(fig,path):
    Path(path).parent.mkdir(exist_ok=True,parents=True)
    fig.savefig(str(path)+'.pdf',bbox_inches='tight');fig.savefig(str(path)+'.png',bbox_inches='tight')
    plt.close(fig)

def individual(name):
    kind=PANELS[name]['kind'];fig=plt.figure(figsize=(9,4) if kind in ['velocity_pair','schematic'] else (5.5,5),constrained_layout=True)
    render(fig,fig.add_gridspec(1,1)[0],name);save(fig,Path('figures/panels',name))

def combined(group):
    names=GROUPS[group]
    if group in ['F2','S3','S5']:
        fig=plt.figure(figsize=(9.4,7),constrained_layout=True);grid=fig.add_gridspec(2,3)
        for row in range(2):
            render(fig,grid[row,:2],names[2*row]);render(fig,grid[row,2],names[2*row+1])
    elif group in ['S1','S2']:
        fig=plt.figure(figsize=(9,(2.35 if group=='S1' else 3.2)*len(names)),constrained_layout=True);grid=fig.add_gridspec(len(names),1)
        for i,name in enumerate(names):render(fig,grid[i],name)
    elif group=='F6':
        fig=plt.figure(figsize=(7,5),constrained_layout=True);render(fig,fig.add_gridspec(1,1)[0],names[0])
    else:
        rows=(len(names)+1)//2;fig=plt.figure(figsize=(11,4.4*rows) if group=='F1' else (9.2,3.2*rows),constrained_layout=True);grid=fig.add_gridspec(rows,2)
        for i,name in enumerate(names):render(fig,grid[i//2,i%2],name)
    fig.suptitle(group+': independent calculation'+(' and a new schematic' if group=='F1' else ''),fontsize=12)
    save(fig,Path('figures',group))

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('panels',nargs='+');args=parser.parse_args()
    names=list(PANELS) if 'all' in args.panels else args.panels
    for name in names:
        if name in PANELS:individual(name)
        else:combined(name)
    if 'all' in args.panels:
        for group in GROUPS:combined(group)
